### ISSUE TITLE
Dead Links I've found.

### ISSUE THREAD

**Issue by SolsticeProjekt** [in4k/in4k.github.io#11]
Greetings.

I'm not sure if I am supposed to provide alternative links, but that would probably keep people from reporting dead links ... besides me simply not being in the matter enough to do so anyway.

Anyhow, I've found dead links and in the thread on pouet (haven't visited it in YEARS, feels so good now ...) it was stated to report whatever is reportable ... so I hereby report. ^_^

Following pages contain dead links:

https://in4k.github.io/wiki/platforms
- "Delphi" linking to https://in4k.github.io/wiki/delphi
- "Turbo Pascal" linking to https://in4k.github.io/wiki/turbo_pascal

https://in4k.github.io/wiki/spheres
- "Tesselate An Octahedron to Make a Sphere" linking to https://www.gamedev.net/resources/_/technical/math-and-physics/tessellate-a-sphere-with-triangles-source-ii-r427

- "enormous topic of research" linking to http://ogre.nu/sphere.htm

- "Random and evenly distributed points on a sphere" linking to http://root.cern.ch/root/html/examples/spheres.C.html

- "the image can be found here." linking to http://local.wasp.uwa.edu.au/~pbourke/rendering/scc3/final/cjjqmo.html

- "here,here and here.", which are three links all linking to http://www.intro-inferno.com/

- "Raytracing a sphere by algebraic and geometric methods" linking to http://devmaster.net/wiki/Ray-sphere_intersection

I hope this helps for a start ... now I'll go back to reading and learning.

o7

**Comment by psenough** [comment]
thanks for reporting. might find some old pages on archive.org

**Comment by psenough** [comment]
couldn't find the original pages so i removed delphi and turbo pascal (no one is doing 4k's in these languages in 2017 anyways).
fixed the broken links on spheres article with links to web.archive.org versions
