### ISSUE TITLE
Some links in "Other resources" don't work

### ISSUE THREAD

**Issue by HorstBaerbel** [in4k/in4k.github.io#14]
Paul Bourkes pages seem to have moved to [http://www.paulbourke.net/](http://www.paulbourke.net/).  
The link to "Useful Maths equations" does not work anymore. It seems to have moved to [http://virtualmathmuseum.org/index.html](http://virtualmathmuseum.org/index.html).  
The program the images for the equations were generated with might be interesting too: "3D-XplorMath" can be found [here](http://www.3d-xplormath.org/).

**Comment by psenough** [comment]
thanks! fixed!
