### ISSUE TITLE
figure out a solution for binaries

### ISSUE THREAD

**Issue by psenough** [in4k/in4k.github.io#7]
there are some binaries still hosted on in4k.undergrund.net (sources, tools, snapshots of pages, videos of talks, pdfs, presentations, tutorials, etc)

repo is not usually the best place to store the binaries but github doesnt have a files section either (like bitbucket does)

also, we will want to snapshot other pages and tools in the future to keep a local copy (in case sites go down) so we need a more permanent solution for storing binaries. any suggestions anyone?

**Comment by arabek** [comment]
Upload to scene.org ftp and link from there?

**Comment by psenough** [comment]
scene.org is more for archives of "releases", and these things feel more like random useful artifacts that we are just backing up because the internet will lose them eventually. but yeah, that might be the best long term solution in the end.

**Comment by cxw42** [comment]
I'll ask menace, but I suspect he won't mind.  Another alternative would be [GitHub LFS](https://help.github.com/articles/about-storage-and-bandwidth-usage/), but that's only 1GB free.

**Comment by glennlunder** [comment]
Hi everyone! Menace here.

Contrary to popular belief, scene.org is a home for all sorts of relevant historical data for the demoscene. If there are source or tools, we're more than happy to make sure that gets preserved. If in doubt about where to put stuff, the /resources/ subdirectory sounds like a good fit for the two mentioned categories at least.

If anyone that is uploading wants to communicate with me directly, the Demozoo slack is a good place for that (@cxw42 is already there) - go to http://slack.demozoo.org to get invited.

**Comment by psenough** [comment]
seems scene.org will be able to hold most of the binaries. sent a mail to ftp@scene.org with a list to wget, once they are up, we just need to go through every page and update url information.

old source code archives might be worth also uploading as new repos to github, for easier browse.

another question follows: shouldn't we want to also zip archive on scene.org dated versions of these new github repos that have been getting forked into the in4k group? could this be automated somehow? maybe with webhooks?

apart from these resources we also should be keeping webpage snapshots of things that get linked as references. archive.org grabbed most of the previously referenced webpages (some of which are now 404) but not all of them. some just felt like deprecated information, so it can just be deleted, but would be nice to have a method to future-proof this a bit better.
webpage snapshots we're previously getting stored under http://in4k.untergrund.net/html_articles/
which i'll be transfering to the repo directly i guess
